# Generated by Django 5.1 on 2024-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='video'),
        ),
    ]
